In [6]:
import pandas as pd
from sqlalchemy import create_engine

In [7]:
engine = create_engine("sqlite:///../apexplanet.db")

print("Database connected successfully using SQLAlchemy!")

Database connected successfully using SQLAlchemy!

In [8]:
query = "SELECT * FROM superstore LIMIT 10;"

df = pd.read_sql(query, engine)

df

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.960,2,0.0,41.9136
1,3,CA-2016-138688,2016-06-12,2016-06-16,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.620,2,0.0,6.8714
2,5,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.368,2,0.2,2.5164
3,6,CA-2014-115812,2014-06-09,2014-06-14,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,...,90032,West,FUR-FU-10001487,Furniture,Furnishings,Eldon Expressions Wood and Plastic Desk Access...,48.860,7,0.0,14.1694
4,7,CA-2014-115812,2014-06-09,2014-06-14,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,...,90032,West,OFF-AR-10002833,Office Supplies,Art,Newell 322,7.280,4,0.0,1.9656
5,9,CA-2014-115812,2014-06-09,2014-06-14,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,...,90032,West,OFF-BI-10003910,Office Supplies,Binders,DXL Angle-View Binders with Locking Rings by S...,18.504,3,0.2,5.7825
6,10,CA-2014-115812,2014-06-09,2014-06-14,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,...,90032,West,OFF-AP-10002892,Office Supplies,Appliances,Belkin F5C206VTEL 6 Outlet Surge,114.900,5,0.0,34.4700
7,13,CA-2017-114412,2017-04-15,2017-04-20,Standard Class,AA-10480,Andrew Allen,Consumer,United States,Concord,...,28027,South,OFF-PA-10002365,Office Supplies,Paper,Xerox 1967,15.552,3,0.2,5.4432
8,14,CA-2016-161389,2016-12-05,2016-12-10,Standard Class,IM-15070,Irene Maddox,Consumer,United States,Seattle,...,98103,West,OFF-BI-10003656,Office Supplies,Binders,Fellowes PB200 Plastic Comb Binding Machine,407.976,3,0.2,132.5922
9,15,US-2015-118983,2015-11-22,2015-11-26,Standard Class,HP-14815,Harold Pawlan,Home Office,United States,Fort Worth,...,76106,Central,OFF-AP-10002311,Office Supplies,Appliances,Holmes Replacement Filter for HEPA Air Cleaner...,68.810,5,0.8,-123.8580

## Business Question 1

### Which category generated the highest total sales?

In [9]:
query = """
SELECT Category,
       SUM(Sales) AS Total_Sales
FROM superstore
GROUP BY Category
ORDER BY Total_Sales DESC;
"""

result = pd.read_sql(query, engine)

result

          Category  Total_Sales
0  Office Supplies  343425.0040
1        Furniture  247877.6984
2       Technology  228415.3530

## Business Question 2

### Which 10 customers generated the highest total sales?

In [10]:
query = """
SELECT "Customer Name",
       SUM(Sales) AS Total_Sales
FROM superstore
GROUP BY "Customer Name"
ORDER BY Total_Sales DESC
LIMIT 10;
"""

result = pd.read_sql(query, engine)

result

     Customer Name  Total_Sales
0       Paul Prost    4196.9280
1  Laura Armstrong    3751.7980
2     Ken Lonsdale    3371.6910
3         John Lee    3338.3520
4    William Brown    3131.9740
5     Noel Staavos    2964.8230
6      Rick Wilson    2879.8910
7    Sally Hughsby    2865.5995
8     Edward Hooks    2821.2100
9    Arthur Gainer    2806.8510

## Business Question 3

### Which region generated the highest total sales?

In [11]:
query = """
SELECT Region,
       SUM(Sales) AS Total_Sales
FROM superstore
GROUP BY Region
ORDER BY Total_Sales DESC;
"""

result = pd.read_sql(query, engine)

result

    Region  Total_Sales
0     West  275810.2625
1     East  232887.4840
2  Central  183440.9134
3    South  127579.3955

## Business Question 4

### Which products generated the highest total sales?

In [14]:
query = """
SELECT "Product Name",
       SUM(Sales) AS Total_Sales
FROM superstore
GROUP BY "Product Name"
ORDER BY Total_Sales DESC
LIMIT 10;
"""

result = pd.read_sql(query, engine)

result

                                       Product Name  Total_Sales
0                        KI Adjustable-Height Table     4036.761
1   Global Wood Trimmed Manager's Task Chair, Khaki     3621.004
2        Situations Contoured Folding Chairs, 4/Set     2959.866
3         Global High-Back Leather Tilter, Burgundy     2841.069
4  Nortel Meridian M3904 Professional Digital phone     2802.618
5               Ibico Hi-Tech Manual Binding System     2653.413
6                 Fellowes Officeware Wire Shelving     2515.240
7                                 Easy-staple paper     2504.192
8                  Logitech Gaming G510s - Keyboard     2362.722
9     Space Solutions HD Industrial Steel Shelving.     2345.388

## Business Question 5

### Which customer segment generated the highest sales?

In [13]:
query = """
SELECT Segment,
       SUM(Sales) AS Total_Sales
FROM superstore
GROUP BY Segment
ORDER BY Total_Sales DESC;
"""

result = pd.read_sql(query, engine)
result

       Segment  Total_Sales
0     Consumer  437711.0838
1    Corporate  240011.9418
2  Home Office  141995.0298

## Business Question 6

### Which ship mode was used the most?

In [15]:
query = """
SELECT "Ship Mode",
       COUNT(*) AS Total_Orders
FROM superstore
GROUP BY "Ship Mode"
ORDER BY Total_Orders DESC;
"""

result = pd.read_sql(query, engine)
result

        Ship Mode  Total_Orders
0  Standard Class          5283
1    Second Class          1708
2     First Class          1359
3        Same Day           477

## Business Question 7

### Which states generated the highest profit?

In [16]:
query = """
SELECT State,
       SUM(Profit) AS Total_Profit
FROM superstore
GROUP BY State
ORDER BY Total_Profit DESC
LIMIT 10;
"""

result = pd.read_sql(query, engine)
result

           State  Total_Profit
0     California    37359.3031
1       New York    20275.1161
2     Washington     8615.1085
3       Michigan     7511.0295
4        Georgia     5535.8972
5       Virginia     5287.1543
6        Indiana     3843.5816
7  Massachusetts     3656.9490
8     New Jersey     3500.3523
9       Kentucky     3242.4227

## Business Question 8

### What is the average discount by category?

In [17]:
query = """
SELECT Category,
       AVG(Discount) AS Average_Discount
FROM superstore
GROUP BY Category;
"""

result = pd.read_sql(query, engine)
result

          Category  Average_Discount
0        Furniture          0.176294
1  Office Supplies          0.159588
2       Technology          0.128404

## Business Question 9

### What is the monthly sales trend?

In [18]:
query = """
SELECT
strftime('%m', "Order Date") AS Month,
SUM(Sales) AS Total_Sales
FROM superstore
GROUP BY Month
ORDER BY Month;
"""

result = pd.read_sql(query, engine)
result

   Month  Total_Sales
0     01   31911.0090
1     02   27949.8704
2     03   60351.2904
3     04   53156.2521
4     05   58021.9144
5     06   61065.0348
6     07   61027.8890
7     08   56371.0245
8     09  107526.8743
9     10   66334.0502
10    11  117834.1100
11    12  118168.7363

## Business Question 10

### Which products generated the highest profit?

In [19]:
query = """
SELECT "Product Name",
       SUM(Profit) AS Total_Profit
FROM superstore
GROUP BY "Product Name"
ORDER BY Total_Profit DESC
LIMIT 10;
"""

result = pd.read_sql(query, engine)
result

                                        Product Name  Total_Profit
0                                  Easy-staple paper     1096.0292
1  Dot Matrix Printer Tape Reel Labels, White, 50...      904.4520
2                                         Xerox 1908      799.3944
3                                         Xerox 1945      756.2655
4                                    Staple envelope      751.6290
5                                          Xerox 189      746.5320
6                                         Xerox 1919      729.6220
7                       Enermax Aurora Lite Keyboard      722.1060
8                   Logitech Gaming G510s - Keyboard      676.5204
9  GE 48" Fluorescent Tube, Cool White Energy Sav...      664.8410

In [20]:
import sys

sys.path.append("../scripts")

from db_connection import get_engine

engine = get_engine()

print("Reusable database utility loaded successfully!")

Reusable database utility loaded successfully!